List<String> panoImages = [
  'cong', //0
  'c2',
  'ngababaixe',
  'nga3sangtao',
  'saue2',
  'nhaxe', //5
  'trcnhaxe',
  'e2',
  'e7',
  'e10',
  'giuae10', //10
  'truocc2',
  'c1c2',
  'sauc2',
  'phongkhaothi',
  'e4nhaxe', //15
  'e5nhaxe',
  'e9',
  'giuae6e9',
];

List<AreHere> youAreHere = [
  AreHere(top: 73, left: 12, endPointId: 1), //cổng->x
  AreHere(top: 73, left: 20, endPointId: 32), //C2->x
  AreHere(top: 52, left: 12, endPointId: 10), //ngã 3 bãi xe->x
  AreHere(top: 40, left: 12, endPointId: 15), //ngã 3 sáng tạo->x
  AreHere(top: 40, left: 36, endPointId: 16), //sau E2->x
  AreHere(top: 40, left: 58, endPointId: 18), //nhà xe->x
  AreHere(top: 52, left: 58, endPointId: 38), //trc nhà xe-> x
  AreHere(top: 52, left: 40, endPointId: 12), //E2->x
  AreHere(top: 26, left: 12, endPointId: 20), //E7->x
  AreHere(top: 12, left: 12, endPointId: 33), //E10->x
  AreHere(top: 12, left: 23, endPointId: 33), //Giữa E10->x
  AreHere(top: 73, left: 32, endPointId: 32), //truovws C2->x
  AreHere(top: 73, left: 43, endPointId: 3), //C1->x
  AreHere(top: 65, left: 40, endPointId: 37), //sau e2 >x
  AreHere(top: 65, left: 56, endPointId: 9), //phong khao thi->x
  AreHere(top: 27, left: 58, endPointId: 23), //e4 nha xe->x
  AreHere(top: 16, left: 58, endPointId: 26), //e5 nha xe->x
  AreHere(top: 5, left: 58, endPointId: 31), // e9-X
  AreHere(top: 0, left: 58, endPointId: 29), // e9 giua e6_x
];
List<Content> content = [
  Content(name: 'C1', content: 'Hội trườngC1'),
  Content(name: 'C2', content: 'C2 - Khu giảng đường'),
  Content(name: 'C3', content: 'Thư viện\nPhòng khảo thí'),
  Content(name: 'E2', content: 'Giảng đường đa năng'),
  Content(name: 'E3', content: 'E3 - Khu giảng đường'),
  Content(name: 'E4', content: 'E4 - Khu giảng đường'),
  Content(name: 'E5', content: 'E5 - Khu giảng đường'),
  Content(name: 'E6', content: 'E6 - Khu giảng đường'),
  Content(name: 'E7', content: 'Phòng máy thực hành'),
  Content(name: 'E9', content: 'E9 - Khu giảng đường'),
  Content(name: 'E10', content: 'E10 - Khu giảng đường'),
  Content(name: 'Bộ môn CNTT', content: 'Bộ môn Công Nghệ Thông Tin'),
  Content(name: 'Ngã 3 sáng tạo', content: 'Ngã 3 sáng tạo'),
  Content(name: 'Khu đào tạo', content: 'Khu đào tạo - 451 Lê Văn Việt'),
  Content(name: 'Cổng chính', content: 'Cổng chính - 450 Lê Văn Việt'),
  Content(name: 'Cổng phụ', content: 'Cổng phụ - 455 Lê Văn Việt'),
  Content(name: 'Nhà xe', content: 'Nhà xe'),
  Content(name: 'Thư viện', content: 'Thư viện'),
  Content(name: 'Phòng khảo thí', content: 'Phòng khảo thí'),
  Content(name: 'Xưởng cơ khí', content: 'Xưởng cơ khí - thực hành'),
  Content(name: '<<= Hướng đi E2', content: '<<= Hướng đi E2'),
  Content(name: 'Hướng đi nhà xe  =>>', content: 'Hướng đi nhà xe  =>>'),
  Content(
      name: 'Hướng đi phòng khảo thí   =>>',
      content: 'UTC2 xin chào các bạn Tân sinh viên !'),
];

const double frontLong = 0.0;
const double rightLong = 90.0;
const double leftLong = -90.0;
const double behideLong = 180.0;

List<List<MyHotspot>> hotSpot = [
  //////Cong 0
  [
    MyHotspot(1, name: 'C2', long: rightLong),
    MyHotspot(2, name: 'E10-E7-E2', long: frontLong),
    //Building
    MyHotspot(1, name: 'C2', long: 75.0, lat: 30.0, type: HotspotType.image),
    MyHotspot(2, name: 'E10', lat: 5.0, type: HotspotType.image, scale: .4),
    MyHotspot(2,
        name: 'E7', long: 10.0, lat: 5.0, type: HotspotType.image, scale: .4),
    MyHotspot(2,
        name: 'Hướng đi nhà xe  =>>',
        long: 15.0,
        lat: 2.0,
        type: HotspotType.image,
        scale: .4),
    MyHotspot(3,
        name: 'C1', long: 90.0, lat: 7.0, type: HotspotType.image, scale: .6),
    MyHotspot(4,
        name: 'E2', long: 47.0, lat: 15.0, type: HotspotType.image, scale: .5),
    MyHotspot(4,
        name: 'Hướng đi phòng khảo thí   =>>',
        long: 60.0,
        lat: 7.0,
        type: HotspotType.image,
        scale: .6),
    MyHotspot(13,
        name: '^', long: 65.0, lat: -2.0, type: HotspotType.arrow, scale: .2),
    MyHotspot(13,
        name: '^', long: 60.0, lat: -4.0, type: HotspotType.arrow, scale: .3),
    MyHotspot(13,
        name: '^', long: 60.0, lat: -10.0, type: HotspotType.arrow, scale: .4),
    MyHotspot(13,
        name: '^', long: 60.0, lat: -20.0, type: HotspotType.arrow, scale: .6),
    MyHotspot(13,
        name: '^', long: 60.0, lat: -30.0, type: HotspotType.arrow, scale: .8),
    MyHotspot(13,
        name: '^', long: 60.0, lat: -40.0, type: HotspotType.arrow, scale: .9),

    MyHotspot(5,
        name: 'Cổng chính',
        long: 180.0,
        lat: 12,
        type: HotspotType.image,
        scale: .9),
    MyHotspot(6,
        name: 'Khu đào tạo',
        long: 150.0,
        lat: 25.0,
        type: HotspotType.image,
        scale: .8),
  ],
  //////C2 1//Cổng qua c2
  [
    MyHotspot(13, name: 'Sau C2', lat: -38, long: rightLong - 34, scale: .95),
    MyHotspot(0, name: 'Cổng', long: -80, lat: -38, scale: .95),
    MyHotspot(11, name: 'C2', long: rightLong + 10),
    MyHotspot(3,
        name: 'C1', long: 105.0, lat: 10, type: HotspotType.image, scale: .8),
    MyHotspot(3, name: 'C2', long: 75.0, lat: 20.0, type: HotspotType.image),
    MyHotspot(3,
        name: 'E2', long: 45.0, lat: 20.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E10', long: 7.0, lat: 7, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'E7', long: 15.0, lat: 10, type: HotspotType.image, scale: .6),
    MyHotspot(6,
        name: 'Khu đào tạo', long: 150.0, lat: 25.0, type: HotspotType.image),
    MyHotspot(5,
        name: 'Cổng chính',
        long: -120.0,
        lat: 20.0,
        scale: .8,
        type: HotspotType.image),
    MyHotspot(4,
        name: 'Hướng đi phòng khảo thí   =>>',
        long: rightLong - 35,
        lat: 7.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(13,
        name: '^',
        long: rightLong - 30,
        lat: -3.0,
        type: HotspotType.arrow,
        scale: .2),
    MyHotspot(13,
        name: '^',
        long: rightLong - 34,
        lat: -4.0,
        type: HotspotType.arrow,
        scale: .2),
    MyHotspot(13,
        name: '^',
        long: rightLong - 34,
        lat: -10.0,
        type: HotspotType.arrow,
        scale: .4),
    MyHotspot(13,
        name: '^',
        long: rightLong - 34,
        lat: -20.0,
        type: HotspotType.arrow,
        scale: .6),
    MyHotspot(13,
        name: '^',
        long: rightLong - 34,
        lat: -30.0,
        type: HotspotType.arrow,
        scale: .8),
    //ra cong
    MyHotspot(0,
        name: '^', long: -80, lat: -7.0, type: HotspotType.arrow, scale: .2),
    MyHotspot(0,
        name: '^', long: -80, lat: -13.0, type: HotspotType.arrow, scale: .4),

    MyHotspot(0,
        name: '^', long: -80, lat: -20.0, type: HotspotType.arrow, scale: .6),
    MyHotspot(0,
        name: '^', long: -80, lat: -30.0, type: HotspotType.arrow, scale: .8),
  ],
  //////Nga ba bai xe 2
  [
    MyHotspot(0, name: 'Cổng', long: behideLong),
    MyHotspot(7, name: 'E2 - Nhà xe', long: rightLong),
    MyHotspot(3, name: 'E10 - E7', long: frontLong + 5),
    MyHotspot(5,
        name: 'E2', long: 80, lat: 20.0, type: HotspotType.image, scale: .9),
    MyHotspot(5,
        name: 'E7', long: 30, lat: 10, type: HotspotType.image, scale: .8),
    MyHotspot(5,
        name: 'E10', long: 5, lat: 7.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'C2', long: 130.0, lat: 16.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'Cổng phụ',
        long: 92,
        lat: 6.0,
        type: HotspotType.image,
        scale: .4),
    MyHotspot(3,
        name: 'Cổng chính',
        long: -177,
        lat: 7.0,
        type: HotspotType.image,
        scale: .4),
  ],
  // ///////Nga ba sang tao 3
  [
    MyHotspot(2, name: 'Cổng-E2', long: behideLong),
    MyHotspot(4, name: 'E3', long: rightLong),
    MyHotspot(8, name: 'E7', long: frontLong + 5),
    MyHotspot(3,
        name: 'E3',
        long: rightLong,
        lat: 8.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'Cổng', long: -177, lat: 5.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'C2', long: 150, lat: 20.0, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: '<<= Hướng đi E2',
        long: 170,
        lat: 1.0,
        type: HotspotType.image,
        scale: .5),
    MyHotspot(3,
        name: 'E7', lat: 12, long: 45, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E10', long: 13, lat: 7.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'E2', long: 105, lat: 28, type: HotspotType.image, scale: .9),
  ],
  ////Sau e2 4
  [
    MyHotspot(5, name: 'Nhà xe', long: 100),
    MyHotspot(3, name: 'Ngã ba sáng tạo', long: -80),
    MyHotspot(3,
        name: 'E4', long: 30, lat: 12.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E3', long: 67, lat: 25.0, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E2', long: 180, lat: 5.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E7', long: -55, lat: 20, type: HotspotType.image, scale: 1),
  ],
  ////////Nha xe 5
  [
    MyHotspot(6, name: 'Trước nhà xe', long: -175),
    MyHotspot(4, name: 'Sau E2', long: -85),
    MyHotspot(15, name: 'E4', long: 6, lat: -12),
    MyHotspot(3,
        name: 'Ngã 3 sáng tạo',
        long: -85,
        lat: 5.0,
        type: HotspotType.image,
        scale: .4),
    MyHotspot(3,
        name: 'C3', long: -175, lat: 16.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'C2', long: -145, lat: 17.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'E2', long: -110, lat: 15.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E4', long: 4, lat: 0.0, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'E5', long: 6, lat: 5.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'E6', long: 6, lat: 9.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'E9', long: 20, lat: 7.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'Nhà xe',
        long: 170,
        lat: 10.0,
        type: HotspotType.image,
        scale: .9),
    MyHotspot(3,
        name: 'Xưởng cơ khí',
        long: 105,
        lat: 3.0,
        type: HotspotType.image,
        scale: .8),
  ],
  ///////truoc nha xe 6
  [
    MyHotspot(14,
        name: 'Phòng khảo thí', lat: -34, scale: .95, long: behideLong + 50),
    MyHotspot(14, name: '^', lat: 3, scale: .2, long: behideLong + 40),
    MyHotspot(14, name: '^', lat: 1, scale: .2, long: behideLong + 45),
    MyHotspot(14, name: '^', lat: -4, scale: .3, long: behideLong + 50),
    MyHotspot(14, name: '^', lat: -14, scale: .5, long: behideLong + 50),
    MyHotspot(14, name: '^', lat: -24, scale: .7, long: behideLong + 50),
    MyHotspot(7, name: 'E2', long: -80),
    MyHotspot(5, name: 'E3', long: 12),
    MyHotspot(3,
        name: 'Phòng khảo thí',
        long: -170.0,
        lat: 20.0,
        type: HotspotType.image,
        scale: .85),
    MyHotspot(3,
        name: 'C3', long: 180, lat: 40.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'Nhà xe', long: 65, lat: 13.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'Xưởng cơ khí',
        long: 85,
        lat: 8.0,
        type: HotspotType.image,
        scale: .8),
    MyHotspot(3,
        name: 'C2', long: -120, lat: 18.0, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'Cổng phụ',
        long: 100,
        lat: 5,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'E3', long: -5, lat: 10, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E9', long: 17, lat: 7, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'E2', long: -70, lat: 10, type: HotspotType.image, scale: .8),
  ],
  ////////E2 7
  [
    MyHotspot(13, name: 'Sau C2', long: behideLong + 10),
    MyHotspot(2, name: 'Cổng', long: -82),
    MyHotspot(6, name: 'Trước nhà xe', long: 100),
    MyHotspot(3,
        name: 'E2', long: 5, lat: 7.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'C2', long: -170, lat: 15.0, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'Cổng chính',
        long: -120,
        lat: 17.0,
        type: HotspotType.image,
        scale: .4),
    MyHotspot(3,
        name: 'C3', long: 135, lat: 18.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'Cổng phụ', long: 98, lat: 3, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'Nhà xe', long: 85, lat: 5, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'Xưởng cơ khí',
        long: 90,
        lat: 7,
        type: HotspotType.image,
        scale: .6),
  ],
  /////E7 8
  [
    MyHotspot(3, name: 'Ngã ba sáng tạo', long: 175),
    MyHotspot(9, name: 'E10', long: frontLong),
    MyHotspot(3,
        name: 'E10', long: 10, lat: 10.0, type: HotspotType.image, scale: .9),
    MyHotspot(
      3,
      name: 'E7',
      long: 90,
      lat: 10.0,
      type: HotspotType.image,
    ),
    MyHotspot(
      3,
      name: 'Cổng',
      long: 175,
      lat: 5.0,
      scale: .4,
      type: HotspotType.image,
    ),
    MyHotspot(3,
        name: 'E2', long: 130, lat: 15.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'C2', long: 150, lat: 12.0, type: HotspotType.image, scale: .5),
  ],
  //////E10 9
  [
    MyHotspot(8, name: 'E7', long: behideLong),
    MyHotspot(10, name: 'E6-E5', long: rightLong),
    MyHotspot(3,
        name: 'E10', long: 15, lat: 5.0, type: HotspotType.image, scale: 1),
    MyHotspot(
      3,
      name: 'Cổng',
      long: 180,
      lat: 5.0,
      scale: .4,
      type: HotspotType.image,
    ),
    MyHotspot(3,
        name: 'E2', long: 140, lat: 20.0, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'E7', lat: 11, long: 135, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'E6', long: 70, lat: 12.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E5', long: 95, lat: 12.0, type: HotspotType.image, scale: .7),
  ],
  //////giua E10 10
  [
    MyHotspot(9, name: 'Cổng', long: leftLong),
    MyHotspot(3, name: 'E10', lat: 5.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E7', long: 165, lat: 10, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'E2', long: 160, lat: 20.0, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'E6', long: 65, lat: 12.0, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E5', long: 95, lat: 12.0, type: HotspotType.image, scale: .9),
    //e6 huong qua e6
    MyHotspot(18,
        name: '^', long: 65, lat: -4.0, type: HotspotType.arrow, scale: .3),
    MyHotspot(18,
        name: '^', long: 65, lat: -10.0, type: HotspotType.arrow, scale: .5),
    MyHotspot(18,
        name: '^', long: 65, lat: -16.0, type: HotspotType.arrow, scale: .7),
    MyHotspot(18,
        name: '^', long: 65, lat: -26.0, type: HotspotType.arrow, scale: .9),
    //e5 huong qua e5
    MyHotspot(16,
        name: '^', long: 95, lat: -4.0, type: HotspotType.arrow, scale: .3),
    MyHotspot(16,
        name: '^', long: 95, lat: -10.0, type: HotspotType.arrow, scale: .5),
    MyHotspot(16,
        name: '^', long: 95, lat: -16.0, type: HotspotType.arrow, scale: .7),
    MyHotspot(16,
        name: '^', long: 95, lat: -26.0, type: HotspotType.arrow, scale: .9),
  ],
  //////truoc C2 11
  [
    MyHotspot(13, name: 'Sau C2', long: rightLong - 20),
    MyHotspot(1, name: 'Cổng', long: leftLong + 5),
    MyHotspot(12, name: 'C1', long: rightLong + 5),
    MyHotspot(3,
        name: 'C1', long: 95.0, lat: 10.0, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'Khu đào tạo',
        long: 180.0,
        lat: 13.0,
        type: HotspotType.image,
        scale: .6),
    MyHotspot(3, name: 'C2', lat: 10.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'Cổng',
        long: -110.0,
        lat: 13.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'C2', long: 75.0, lat: 12.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'C3', long: 85.0, lat: 13.0, type: HotspotType.image, scale: .4),
  ],
  //////C1 C2 12
  [
    MyHotspot(13, name: 'Sau C2', long: leftLong + 30),
    MyHotspot(11, name: 'C2', long: leftLong),
    MyHotspot(3,
        name: 'C1',
        long: rightLong,
        lat: 5.0,
        type: HotspotType.image,
        scale: 1),
    MyHotspot(3,
        name: 'Khu đào tạo',
        long: -170.0,
        lat: 10.0,
        type: HotspotType.image,
        scale: .6),
    MyHotspot(3,
        name: 'Cổng',
        long: -110.0,
        lat: 10.0,
        type: HotspotType.image,
        scale: .5),
    MyHotspot(3,
        name: 'C2', long: -60.0, lat: 7.0, type: HotspotType.image, scale: 1),
  ],
  //////sau C2 13
  [
    MyHotspot(1, name: 'Cổng', long: leftLong, lat: -34, scale: .95),
    MyHotspot(7, name: 'E2', long: frontLong),
    MyHotspot(14,
        name: 'Phòng khảo thí', lat: -34, long: rightLong, scale: .95),
    MyHotspot(11, name: 'Trước C2', long: behideLong),
    MyHotspot(3,
        name: 'C2', long: -180.0, lat: 7.0, type: HotspotType.image, scale: 1),
    MyHotspot(3, name: 'E2', lat: 17.0, type: HotspotType.image, scale: .8),
    MyHotspot(3,
        name: 'Phòng khảo thí',
        long: rightLong,
        lat: 10.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'Nhà xe',
        long: rightLong - 38,
        lat: 5.0,
        type: HotspotType.image,
        scale: .5),
    MyHotspot(3,
        name: 'E3',
        long: rightLong - 55,
        lat: 4.0,
        type: HotspotType.image,
        scale: .6),
    MyHotspot(13,
        name: '^',
        long: leftLong,
        lat: -4.0,
        type: HotspotType.arrow,
        scale: .3),
    MyHotspot(13,
        name: '^',
        long: leftLong,
        lat: -10.0,
        type: HotspotType.arrow,
        scale: .5),
    MyHotspot(13,
        name: '^',
        long: leftLong,
        lat: -16.0,
        type: HotspotType.arrow,
        scale: .7),
    MyHotspot(13,
        name: '^',
        long: leftLong,
        lat: -26.0,
        type: HotspotType.arrow,
        scale: .9),
    //thảo khi
    MyHotspot(13,
        name: '^',
        long: rightLong,
        lat: -3.0,
        type: HotspotType.arrow,
        scale: .2),
    MyHotspot(13,
        name: '^',
        long: rightLong,
        lat: -6.0,
        type: HotspotType.arrow,
        scale: .3),
    MyHotspot(13,
        name: '^',
        long: rightLong,
        lat: -10.0,
        type: HotspotType.arrow,
        scale: .5),
    MyHotspot(13,
        name: '^',
        long: rightLong,
        lat: -16.0,
        type: HotspotType.arrow,
        scale: .7),
    MyHotspot(13,
        name: '^',
        long: rightLong,
        lat: -26.0,
        type: HotspotType.arrow,
        scale: .9),
  ],
  //////Phong khao thi 14
  [
    MyHotspot(13, name: 'Sau C2', long: leftLong),
    MyHotspot(6, name: 'Trước nhà xe', lat: -34, scale: .95, long: frontLong),
    MyHotspot(6, name: '^', lat: -6, scale: .2, long: frontLong + 8),
    MyHotspot(6, name: '^', lat: -8, scale: .2, long: frontLong + 6),
    MyHotspot(6, name: '^', lat: -11, scale: .3, long: frontLong + 4),
    MyHotspot(6, name: '^', lat: -16, scale: .5, long: frontLong + 2),
    MyHotspot(6, name: '^', lat: -24, scale: .7, long: frontLong),
    MyHotspot(3,
        name: 'E2', long: -50.0, lat: 4.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'C1', long: -160.0, lat: 7.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'Phòng khảo thí',
        long: 80,
        lat: 7.0,
        type: HotspotType.image,
        scale: 1),
    MyHotspot(3,
        name: 'Thư viện',
        long: 150,
        lat: 7.0,
        type: HotspotType.image,
        scale: 1),
    MyHotspot(3,
        name: 'Nhà xe', long: 40, lat: 7.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E3',
        long: frontLong,
        lat: 7.0,
        type: HotspotType.image,
        scale: .6),
    //thu vien
  ],
  //////E4 nhà xe 15
  [
    MyHotspot(5, name: 'E3 - Nhà xe', long: behideLong),
    MyHotspot(16, name: 'E5-E6-E9', long: frontLong),
    MyHotspot(3,
        name: 'C3',
        long: behideLong,
        lat: 15.0,
        type: HotspotType.image,
        scale: .4),
    MyHotspot(3,
        name: 'E2', long: -145, lat: 25.0, type: HotspotType.image, scale: .5),
    MyHotspot(3,
        name: 'E3', long: -170, lat: 10.0, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E4', long: -90.0, lat: 4, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E7', long: -90.0, lat: 15, type: HotspotType.image, scale: .4),
    MyHotspot(3, name: 'E5', lat: 5.0, type: HotspotType.image, scale: .6),
    MyHotspot(3, name: 'E6', lat: 9.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'E9', long: 10, lat: 7.0, type: HotspotType.image, scale: .4),
    MyHotspot(3,
        name: 'Nhà xe',
        long: 160,
        lat: 5.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'Xưởng cơ khí',
        long: 105,
        lat: 3.0,
        type: HotspotType.image,
        scale: .8),
  ],
  //////E5 nhà xe 16
  [
    MyHotspot(15, name: 'E4 - Nhà xe', long: behideLong),
    MyHotspot(17, name: 'E9', long: frontLong),
    MyHotspot(3,
        name: 'E3', long: -178, lat: 11.0, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'E6', long: -5, lat: 10.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E9', long: 20, lat: 7.0, type: HotspotType.image, scale: .7),
    MyHotspot(3,
        name: 'E5', long: -80, lat: 4.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'Bộ môn CNTT',
        long: -100,
        lat: 10.0,
        type: HotspotType.image,
        scale: .7),
    MyHotspot(3,
        name: 'E4', long: -150, lat: 10.0, type: HotspotType.image, scale: .9),
    MyHotspot(3,
        name: 'E2', long: -140, lat: 20, type: HotspotType.image, scale: .6),
    MyHotspot(3,
        name: 'Xưởng cơ khí',
        long: 90.0,
        lat: 4.0,
        type: HotspotType.image,
        scale: 1),
    MyHotspot(3,
        name: 'Nhà xe',
        long: 150,
        lat: 5.0,
        type: HotspotType.image,
        scale: .8),
  ],
  //////E9 17
  [
    MyHotspot(16, name: 'E5 - Nhà xe', long: behideLong),
    MyHotspot(18, name: 'E6 - E9', long: frontLong),
    MyHotspot(3,
        name: 'E9', long: 45, lat: 4.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E6', long: -45, lat: 4.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E5', long: -150, lat: 10.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'Nhà xe',
        long: 145.0,
        lat: 7.0,
        type: HotspotType.image,
        scale: 1),
  ],
  //giua e6 và e9
  [
    MyHotspot(17, name: 'E9', long: behideLong),
    MyHotspot(3,
        name: 'E9', long: 90, lat: 4.0, type: HotspotType.image, scale: 1),
    MyHotspot(3,
        name: 'E6', long: -90, lat: 4.0, type: HotspotType.image, scale: 1),
  ],
];

class MyHotspot {
  int id;
  double lat, long;
  String name;
  HotspotType type;
  double scale;

  MyHotspot(
    this.id, {
    this.lat = -15.0,
    this.long = 0.0,
    this.name = '',
    this.type = HotspotType.arrow,
    this.scale = 1.0,
  });
}

enum HotspotType { arrow, image }

class AreHere {
  double top;
  double left;
  int endPointId;
  AreHere({this.top, this.left, this.endPointId});
}

class Content {
  String name;
  String content;
  Content({
    this.name,
    this.content,
  });
}
