name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  panorama: 
    path: ../
  image_picker: ^0.6.3+4
  tabbar: ^0.1.1
  bubble_tab_indicator: ^0.1.4
  html: ^0.14.0+4
  web_scraper: ^0.0.9
  cached_network_image: ^2.5.0
  rxdart: ^0.25.0
  flutter_spinkit: ^4.1.2
  countup: ^0.1.3
  percent_indicator: "^2.1.7+2"
  photo_view: ^0.10.3
  url_launcher: ^5.6.0
  im_stepper: ^0.1.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "Trip Map"


flutter_icons:
  image_path_android: "assets/icon_launcher.png" 
  image_path_ios: "assets/icon_launcher_ios.png" 
  android: true
  ios: true


flutter:
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: font/Nunito-Regular.ttf
        - asset: font/Nunito-Italic.ttf
  uses-material-design: true