name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  panorama: ^0.4.0
  image_picker: ^0.7.5+2
  tabbar: ^0.1.1
  bubble_tab_indicator: ^0.1.4
  html: ^0.15.0
  web_scraper: ^0.1.4
  cached_network_image: ^2.5.0
  rxdart: ^0.25.0
  flutter_spinkit: ^5.0.0
  countup: ^0.1.3
  percent_indicator: ^3.0.1
  photo_view: ^0.11.1
  url_launcher: ^6.0.3
  im_stepper: ^0.1.2+10
  avatar_glow: ^2.0.1
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  sensors: ^2.0.0
  geolocator: ^7.0.3
  shared_preferences: ^2.0.5
  permission_handler: ^7.1.0
  qrscan: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "Trip Map"


flutter_icons:
  image_path_android: "assets/icon_launcher.png" 
  image_path_ios: "assets/icon_launcher_ios.jpg" 
  android: true
  ios: true


flutter:
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: font/Nunito-Regular.ttf
        - asset: font/Nunito-Italic.ttf
  uses-material-design: true